In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:/Users/User/Desktop/play_tennis.csv")

In [3]:
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [4]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [5]:
py = 9/14
pn = 5/14

In [7]:
pd.crosstab(df['outlook'] , df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [8]:
Pon = 0
Prn = 2/5
Psn = 3/5

Poy = 4/9
Pry = 3/9
Psy = 2/9

In [9]:
pd.crosstab(df['temp'] , df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [10]:
PnCool = 1/5
PnHot = 2/5
PnMild = 2/5

PyCool = 3/9
PyHot = 2/9
PyMild = 4/9

In [11]:
pd.crosstab(df['humidity'] , df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [12]:
PnHigh = 4/5
PnNormal = 1/5
PyHigh = 3/9
PyNormal = 6/9

In [13]:
pd.crosstab(df['wind'] , df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [14]:
PnStrong = 3/5
PnWeak = 2/5
PyStrong = 3/9
PyWeak = 6/9

In [15]:
Yes = py * Psy * PyHot * PyHigh * PyWeak

In [16]:
print(Yes)

0.007054673721340388

In [17]:
No = pn * Psn * PnHot * PnHigh * PnWeak

In [18]:
print(No)

0.02742857142857143

In [26]:
ans_dict = {"Yes" : Yes , "No" : No}
ans_dict.values()

dict_values([0.007054673721340388, 0.02742857142857143])

In [27]:
ans = max(ans_dict.values())

In [29]:
print("Answer Is : " , ans_dict.)

Answer Is :  None

# **`This Means Player Does not play when outlook is sunny temp is Hot Humidity is High and Wind is Weak`**